In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
timeseries = pd.read_csv("../data/hf_dataset/sepsis_timeseries_hourly.csv")
cohort = pd.read_csv("../data/hf_dataset/sepsis_cohort.csv")

In [4]:
print("Timeseries Shape:", timeseries.shape)
print("Cohort Shape:", cohort.shape)

display(timeseries.head())
display(cohort.head())

Timeseries Shape: (851717, 64)
Cohort Shape: (32971, 12)

,stay_id,hour,heart_rate,resp_rate,temperature,sbp,dbp,mbp,spo2,gcs,urineoutput_last,urineoutput_sum,wbc,hemoglobin,hematocrit,platelet,creatinine,bun,sodium,potassium,chloride,bicarbonate,calcium,aniongap,glucose_lab,albumin,bilirubin_total,inr,pt,ptt,lactate,bands,crp,magnesium,starttime,endtime,pao2fio2ratio_novent,pao2fio2ratio_vent,rate_epinephrine,rate_norepinephrine,rate_dopamine,rate_dobutamine,meanbp_min,gcs_min,urineoutput_24hr,uo_tm_24hr,uo_24hr,bilirubin_max,creatinine_max,platelet_min,respiration,coagulation,liver,cardiovascular,cns,renal,sofa_score,respiration_24hours,coagulation_24hours,liver_24hours,cardiovascular_24hours,cns_24hours,renal_24hours,sofa_24hours
0,30000484,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2136-01-14 17:23:32,2136-01-14 18:23:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
1,30000484,1,99.0,16.0,35.56,101.0,75.0,81.0,100.0,6.0,260.0,260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2136-01-14 18:23:32,2136-01-14 19:23:32,NaN,NaN,NaN,NaN,NaN,NaN,81.0,6.0,260.0,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,NaN,3.0,0,0,0,0,3,0,3
2,30000484,2,88.0,14.0,NaN,92.0,43.0,55.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2136-01-14 19:23:32,2136-01-14 20:23:32,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,0,0,0,1,3,0,4
3,30000484,3,87.0,13.0,NaN,97.0,51.0,62.0,100.0,NaN,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,56.5,NaN,2136-01-14 20:23:32,2136-01-14 21:23:32,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NaN,360.0,2.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,0,0,0,1,3,0,4
4,30000484,4,92.0,18.0,NaN,128.0,66.0,82.0,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2136-01-14 21:23:32,2136-01-14 22:23:32,NaN,NaN,NaN,NaN,NaN,NaN,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0,0,0,1,3,0,4

,subject_id,hadm_id,stay_id,icu_intime,icu_outtime,sepsis_time,suspected_infection_time,window_end_uncapped,window_end,gender,age,n_hours
0,18421337,22413411,30000484,2136-01-14 17:23:32,2136-01-17 04:53:08,2136-01-14 19:00:00,2136-01-14 18:10:00,2136-01-15 17:23:32,2136-01-15 17:23:32,M,92,24
1,12207593,22795209,30000646,2194-04-29 01:39:22,2194-05-03 18:23:48,2194-04-29 11:00:00,2194-04-29 01:00:00,2194-04-30 01:39:22,2194-04-30 01:39:22,M,44,24
2,16513856,24463832,30001446,2186-04-12 03:49:00,2186-04-13 19:45:47,2186-04-12 04:00:00,2186-04-11 08:20:00,2186-04-13 03:49:00,2186-04-13 03:49:00,M,56,24
3,10656173,25778760,30001555,2177-09-27 11:23:13,2177-09-28 18:26:00,2177-09-27 12:00:00,2177-09-27 07:21:00,2177-09-28 11:23:13,2177-09-28 11:23:13,F,34,24
4,17921898,28841024,30002415,2126-12-17 09:54:03,2126-12-18 10:15:01,2126-12-17 12:00:00,2126-12-16 15:05:00,2126-12-18 09:54:03,2126-12-18 09:54:03,F,72,24

In [5]:
missing = (
    timeseries.isnull()
    .mean()
    .sort_values(ascending=False)
    * 100
)

display(missing)

crp                       99.914995
bands                     99.330646
rate_dobutamine           99.237305
pao2fio2ratio_novent      98.984757
rate_dopamine             98.764613
                            ...
liver_24hours              0.000000
cardiovascular_24hours     0.000000
cns_24hours                0.000000
renal_24hours              0.000000
sofa_24hours               0.000000
Length: 64, dtype: float64

In [6]:
selected_features = [

    # Patient ID
    "stay_id",

    # Time
    "hour",

    # Vital Signs
    "heart_rate",
    "resp_rate",
    "temperature",
    "sbp",
    "dbp",
    "mbp",
    "spo2",
    "gcs",

    # Kidney
    "creatinine",
    "bun",
    "urineoutput_last",
    "urineoutput_sum",
    "urineoutput_24hr",

    # Blood
    "wbc",
    "hemoglobin",
    "hematocrit",
    "platelet",
    "bands",

    # Electrolytes
    "sodium",
    "potassium",
    "chloride",
    "bicarbonate",
    "calcium",
    "magnesium",
    "aniongap",

    # Liver
    "albumin",
    "bilirubin_total",
    "bilirubin_max",

    # Coagulation
    "inr",
    "pt",
    "ptt",

    # Inflammatory
    "crp",
    "lactate",

    # Oxygenation
    "pao2fio2ratio_novent",
    "pao2fio2ratio_vent",

    # Others
    "glucose_lab"
]

In [7]:
print("Duplicate columns in timeseries:")
print(timeseries.columns[timeseries.columns.duplicated()])
print("Total duplicate columns:", timeseries.columns.duplicated().sum())

Duplicate columns in timeseries:
Index([], dtype='str')
Total duplicate columns: 0

In [8]:
from collections import Counter

counts = Counter(selected_features)

duplicates = {k: v for k, v in counts.items() if v > 1}

print(duplicates)

{}

In [9]:
print(len(selected_features))
print(len(set(selected_features)))

38
38

In [10]:
selected_features = list(dict.fromkeys(selected_features))
print(len(selected_features))
print(len(set(selected_features)))

38
38

In [11]:
model_a = timeseries[selected_features].copy()

print(model_a.shape)
print("Duplicate Columns:", model_a.columns.duplicated().sum())

(851717, 38)
Duplicate Columns: 0

In [12]:
# Shock Index = HR / SBP

model_a["shock_index"] = (
    model_a["heart_rate"] /
    model_a["sbp"]
)

model_a[
    ["heart_rate", "sbp", "shock_index"]
].head(10) # above 1 sepsis risk and between 0.7 to 1 is suspicious of sepsis

   heart_rate    sbp  shock_index
0         NaN    NaN          NaN
1        99.0  101.0     0.980198
2        88.0   92.0     0.956522
3        87.0   97.0     0.896907
4        92.0  128.0     0.718750
5        83.0   78.0     1.064103
6        81.0   86.0     0.941860
7        91.0  134.0     0.679104
8        90.0   92.0     0.978261
9        84.0   90.0     0.933333

In [13]:
# mean atrial pressure
model_a["map_calculated"] = (
    model_a["dbp"] +
    (model_a["sbp"] - model_a["dbp"]) / 3
)

model_a[
    ["sbp", "dbp", "mbp", "map_calculated"]
].head() # below 65 is risk of sepsis

     sbp   dbp   mbp  map_calculated
0    NaN   NaN   NaN             NaN
1  101.0  75.0  81.0       83.666667
2   92.0  43.0  55.0       59.333333
3   97.0  51.0  62.0       66.333333
4  128.0  66.0  82.0       86.666667

In [14]:
#  kidney fn ratio denotes kidneys function because during sepsis kidney gets affected mainly
model_a["bun_creatinine_ratio"] = (
    model_a["bun"] /
    model_a["creatinine"]
)

model_a[
    ["bun", "creatinine", "bun_creatinine_ratio"]
].head()
model_a[
    model_a["bun_creatinine_ratio"].notna()
][["bun", "creatinine", "bun_creatinine_ratio"]].head(10)

      bun  creatinine  bun_creatinine_ratio
11   47.0         1.2             39.166667
24   12.0         0.9             13.333333
28   12.0         1.0             12.000000
41    9.0         0.6             15.000000
49   70.0         2.7             25.925926
58   70.0         2.5             28.000000
97    9.0         0.6             15.000000
104   9.0         0.7             12.857143
112  10.0         0.8             12.500000
123  22.0         1.9             11.578947

In [15]:
print(model_a["bun_creatinine_ratio"].notna().sum())
model_a[
    model_a["bun_creatinine_ratio"].notna()
][["bun", "creatinine", "bun_creatinine_ratio"]].head(10)

80173

      bun  creatinine  bun_creatinine_ratio
11   47.0         1.2             39.166667
24   12.0         0.9             13.333333
28   12.0         1.0             12.000000
41    9.0         0.6             15.000000
49   70.0         2.7             25.925926
58   70.0         2.5             28.000000
97    9.0         0.6             15.000000
104   9.0         0.7             12.857143
112  10.0         0.8             12.500000
123  22.0         1.9             11.578947

In [16]:
model_a["spo2_deficit"] = (
    100 -
    model_a["spo2"]
)

model_a[
    ["spo2", "spo2_deficit"]
].head()

    spo2  spo2_deficit
0    NaN           NaN
1  100.0           0.0
2  100.0           0.0
3  100.0           0.0
4   98.0           2.0

In [17]:
print("="*50)
print("Model Shape:", model_a.shape)
print("Number of Features:", model_a.shape[1])

print("\nEngineered Features Added:")
engineered = [
    "shock_index",
    "pulse_pressure",
    "map_calculated",
    "bun_creatinine_ratio",
    "spo2_deficit"
]

for feature in engineered:
    print("✓", feature)

print("="*50)

==================================================
Model Shape: (851717, 42)
Number of Features: 42

Engineered Features Added:
✓ shock_index
✓ pulse_pressure
✓ map_calculated
✓ bun_creatinine_ratio
✓ spo2_deficit
==================================================

In [18]:
# heart rate change over last hour
model_a = model_a.sort_values(
    ["stay_id","hour"]
).reset_index(drop=True)

In [19]:
model_a["heart_rate_prev"] = (
    model_a
    .groupby("stay_id")["heart_rate"] # groupby is used to treat every stay id as seperate one and [heart rate] to choose the category from the table
    .shift(1) # shift (1) used to choose the previous one of the category
)

In [20]:
model_a[
    [
        "stay_id",
        "hour",
        "heart_rate",
        "heart_rate_prev"
    ]
].head(15)

     stay_id  hour  heart_rate  heart_rate_prev
0   30000484     0         NaN              NaN
1   30000484     1        99.0              NaN
2   30000484     2        88.0             99.0
3   30000484     3        87.0             88.0
4   30000484     4        92.0             87.0
5   30000484     5        83.0             92.0
6   30000484     6        81.0             83.0
7   30000484     7        91.0             81.0
8   30000484     8        90.0             91.0
9   30000484     9        84.0             90.0
10  30000484    10        85.0             84.0
11  30000484    11        84.0             85.0
12  30000484    12        91.0             84.0
13  30000484    13        83.0             91.0
14  30000484    14        90.0             83.0

In [21]:
# heart rate change
model_a["heart_rate_delta"] = (
    model_a["heart_rate"] -
    model_a["heart_rate_prev"]
)

In [22]:
model_a[
    [
        "heart_rate",
        "heart_rate_prev",
        "heart_rate_delta" # delta fn is used to identify the trend instead of flase alarming because sudden heart rate rise
    ]
].head(10)

   heart_rate  heart_rate_prev  heart_rate_delta
0         NaN              NaN               NaN
1        99.0              NaN               NaN
2        88.0             99.0             -11.0
3        87.0             88.0              -1.0
4        92.0             87.0               5.0
5        83.0             92.0              -9.0
6        81.0             83.0              -2.0
7        91.0             81.0              10.0
8        90.0             91.0              -1.0
9        84.0             90.0              -6.0

In [23]:
# respiratory rate
model_a["resp_rate_prev"] = (
    model_a
    .groupby("stay_id")["resp_rate"]
    .shift(1)
)

In [24]:
model_a["resp_rate_delta"] = (
    model_a["resp_rate"] -
    model_a["resp_rate_prev"]
)

model_a[
    [
        "stay_id",
        "hour",
        "resp_rate",
        "resp_rate_prev",
        "resp_rate_delta"
    ]
].head(15)

     stay_id  hour  resp_rate  resp_rate_prev  resp_rate_delta
0   30000484     0        NaN             NaN              NaN
1   30000484     1       16.0             NaN              NaN
2   30000484     2       14.0            16.0             -2.0
3   30000484     3       13.0            14.0             -1.0
4   30000484     4       18.0            13.0              5.0
5   30000484     5       14.0            18.0             -4.0
6   30000484     6       15.0            14.0              1.0
7   30000484     7       17.0            15.0              2.0
8   30000484     8       13.0            17.0             -4.0
9   30000484     9       12.0            13.0             -1.0
10  30000484    10       12.0            12.0              0.0
11  30000484    11       14.0            12.0              2.0
12  30000484    12       19.0            14.0              5.0
13  30000484    13       13.0            19.0             -6.0
14  30000484    14       14.0            13.0              1.0

In [25]:
# previous temperature
model_a["temperature_prev"] = (
    model_a
    .groupby("stay_id")["temperature"]
    .shift(1)
)
model_a["temperature_delta"] = (
    model_a["temperature"] -
    model_a["temperature_prev"]
)
model_a[
    [
        "stay_id",
        "hour",
        "temperature",
        "temperature_prev",
        "temperature_delta"
    ]
].head(15)

     stay_id  hour  temperature  temperature_prev  temperature_delta
0   30000484     0          NaN               NaN                NaN
1   30000484     1        35.56               NaN                NaN
2   30000484     2          NaN             35.56                NaN
3   30000484     3          NaN               NaN                NaN
4   30000484     4          NaN               NaN                NaN
5   30000484     5          NaN               NaN                NaN
6   30000484     6        35.56               NaN                NaN
7   30000484     7          NaN             35.56                NaN
8   30000484     8          NaN               NaN                NaN
9   30000484     9          NaN               NaN                NaN
10  30000484    10        35.78               NaN                NaN
11  30000484    11          NaN             35.78                NaN
12  30000484    12          NaN               NaN                NaN
13  30000484    13          NaN               NaN                NaN
14  30000484    14        35.83               NaN                NaN

In [26]:
# previous sbp
model_a["sbp_prev"] = (
    model_a
    .groupby("stay_id")["sbp"]
    .shift(1)
)
model_a["sbp_delta"] = (
    model_a["sbp"] -
    model_a["sbp_prev"]
)
model_a[
    [
        "stay_id",
        "hour",
        "sbp",
        "sbp_prev",
        "sbp_delta"
    ]
].head(15)

     stay_id  hour    sbp  sbp_prev  sbp_delta
0   30000484     0    NaN       NaN        NaN
1   30000484     1  101.0       NaN        NaN
2   30000484     2   92.0     101.0       -9.0
3   30000484     3   97.0      92.0        5.0
4   30000484     4  128.0      97.0       31.0
5   30000484     5   78.0     128.0      -50.0
6   30000484     6   86.0      78.0        8.0
7   30000484     7  134.0      86.0       48.0
8   30000484     8   92.0     134.0      -42.0
9   30000484     9   90.0      92.0       -2.0
10  30000484    10   86.0      90.0       -4.0
11  30000484    11   92.0      86.0        6.0
12  30000484    12  121.0      92.0       29.0
13  30000484    13   88.0     121.0      -33.0
14  30000484    14  113.0      88.0       25.0

In [27]:
# previous map
model_a["mbp_prev"] = (
    model_a
    .groupby("stay_id")["mbp"]
    .shift(1)
)
model_a["mbp_delta"] = (
    model_a["mbp"] -
    model_a["mbp_prev"]
)
model_a[
    [
        "stay_id",
        "hour",
        "mbp",
        "mbp_prev",
        "mbp_delta"
    ]
].head(15)

     stay_id  hour   mbp  mbp_prev  mbp_delta
0   30000484     0   NaN       NaN        NaN
1   30000484     1  81.0       NaN        NaN
2   30000484     2  55.0      81.0      -26.0
3   30000484     3  62.0      55.0        7.0
4   30000484     4  82.0      62.0       20.0
5   30000484     5  50.0      82.0      -32.0
6   30000484     6  52.0      50.0        2.0
7   30000484     7  84.0      52.0       32.0
8   30000484     8  58.0      84.0      -26.0
9   30000484     9  54.0      58.0       -4.0
10  30000484    10  60.0      54.0        6.0
11  30000484    11  58.0      60.0       -2.0
12  30000484    12  66.0      58.0        8.0
13  30000484    13  50.0      66.0      -16.0
14  30000484    14  75.0      50.0       25.0

In [28]:
# previous spo2
model_a["spo2_prev"] = (
    model_a
    .groupby("stay_id")["spo2"]
    .shift(1)
)
model_a["spo2_delta"] = (
    model_a["spo2"] -
    model_a["spo2_prev"]
)
model_a[
    [
        "stay_id",
        "hour",
        "spo2",
        "spo2_prev",
        "spo2_delta"
    ]
].head(15)

     stay_id  hour   spo2  spo2_prev  spo2_delta
0   30000484     0    NaN        NaN         NaN
1   30000484     1  100.0        NaN         NaN
2   30000484     2  100.0      100.0         0.0
3   30000484     3  100.0      100.0         0.0
4   30000484     4   98.0      100.0        -2.0
5   30000484     5  100.0       98.0         2.0
6   30000484     6  100.0      100.0         0.0
7   30000484     7  100.0      100.0         0.0
8   30000484     8  100.0      100.0         0.0
9   30000484     9  100.0      100.0         0.0
10  30000484    10  100.0      100.0         0.0
11  30000484    11   99.0      100.0        -1.0
12  30000484    12  100.0       99.0         1.0
13  30000484    13  100.0      100.0         0.0
14  30000484    14  100.0      100.0         0.0

In [29]:
#glasgow coma scale measure a person's level of consciousness after a brain injury or during critical illness (like sepsis)
model_a["gcs_prev"] = (
    model_a
    .groupby("stay_id")["gcs"]
    .shift(1)
)
model_a["gcs_delta"] = (
    model_a["gcs"] -
    model_a["gcs_prev"]
)
model_a[
    [
        "stay_id",
        "hour",
        "gcs",
        "gcs_prev",
        "gcs_delta"

    ]
].head(15)

     stay_id  hour   gcs  gcs_prev  gcs_delta
0   30000484     0   NaN       NaN        NaN
1   30000484     1   6.0       NaN        NaN
2   30000484     2   NaN       6.0        NaN
3   30000484     3   NaN       NaN        NaN
4   30000484     4   NaN       NaN        NaN
5   30000484     5   NaN       NaN        NaN
6   30000484     6   NaN       NaN        NaN
7   30000484     7  11.0       NaN        NaN
8   30000484     8   NaN      11.0        NaN
9   30000484     9   NaN       NaN        NaN
10  30000484    10   NaN       NaN        NaN
11  30000484    11  11.0       NaN        NaN
12  30000484    12   NaN      11.0        NaN
13  30000484    13   NaN       NaN        NaN
14  30000484    14   5.0       NaN        NaN

In [30]:
#ROLLING FEATURE mean
model_a["heart_rate_roll3_mean"] = (
    model_a
    .groupby("stay_id")["heart_rate"]
    .transform(
        lambda x: x.rolling(
            window = 3,
            min_periods = 1,

        ).mean()
    )
)

In [31]:
#ROLLING FEATURE mean
model_a["heart_rate_roll6_mean"] = (
    model_a
    .groupby("stay_id")["heart_rate"]
    .transform(
        lambda x: x.rolling(
            window = 6,
            min_periods = 1,

        ).mean()
    )
)

In [32]:
model_a[
    [
        "stay_id",
        "hour",
        "heart_rate",
        "heart_rate_roll3_mean"
    ]
].head(15)

     stay_id  hour  heart_rate  heart_rate_roll3_mean
0   30000484     0         NaN                    NaN
1   30000484     1        99.0              99.000000
2   30000484     2        88.0              93.500000
3   30000484     3        87.0              91.333333
4   30000484     4        92.0              89.000000
5   30000484     5        83.0              87.333333
6   30000484     6        81.0              85.333333
7   30000484     7        91.0              85.000000
8   30000484     8        90.0              87.333333
9   30000484     9        84.0              88.333333
10  30000484    10        85.0              86.333333
11  30000484    11        84.0              84.333333
12  30000484    12        91.0              86.666667
13  30000484    13        83.0              86.000000
14  30000484    14        90.0              88.000000

In [36]:
# ROllING STD
model_a["heart_rate_roll3_std"] = (
    model_a
    .groupby("stay_id")["heart_rate"]
    .transform(
        lambda x: x.rolling(
            window=3,
            min_periods=1
        ).std()
    )
)

In [37]:
# ROLLING MAXIMUM
model_a["heart_rate_roll3_max"] = (
    model_a
    .groupby("stay_id")["heart_rate"]
    .transform(
        lambda x: x.rolling(
            window=3,
            min_periods=1
        ).max()
    )
)

In [38]:
# ROLLING MINIMUM
model_a["heart_rate_roll3_min"] = (
    model_a
    .groupby("stay_id")["heart_rate"]
    .transform(
        lambda x: x.rolling(
            window=3,
            min_periods=1
        ).min()
    )
)

In [43]:
model_a[
    [
        "stay_id",
        "hour",
        "heart_rate",
        "heart_rate_roll3_mean",
        "heart_rate_roll6_mean",
        "heart_rate_roll3_std",
        "heart_rate_roll3_max",
        "heart_rate_roll3_min"
    ]
].head(15)

,stay_id,hour,heart_rate,heart_rate_roll3_mean,heart_rate_roll6_mean,heart_rate_roll3_std,heart_rate_roll3_max,heart_rate_roll3_min
0,30000484,0,NaN,NaN,NaN,NaN,NaN,NaN
1,30000484,1,99.0,99.000000,99.000000,NaN,99.0,99.0
2,30000484,2,88.0,93.500000,93.500000,7.778175,99.0,88.0
3,30000484,3,87.0,91.333333,91.333333,6.658328,99.0,87.0
4,30000484,4,92.0,89.000000,89.000000,2.645751,92.0,87.0
5,30000484,5,83.0,87.333333,87.333333,4.509250,92.0,83.0
6,30000484,6,81.0,85.333333,85.333333,5.859465,92.0,81.0
7,30000484,7,91.0,85.000000,85.000000,5.291503,91.0,81.0
8,30000484,8,90.0,87.333333,87.333333,5.507571,91.0,81.0
9,30000484,9,84.0,88.333333,88.333333,3.785939,91.0,84.0
10,30000484,10,85.0,86.333333,86.333333,3.214550,90.0,84.0
11,30000484,11,84.0,84.333333,84.333333,0.577350,85.0,84.0
12,30000484,12,91.0,86.666667,86.666667,3.785939,91.0,84.0
13,30000484,13,83.0,86.000000,86.000000,4.358899,91.0,83.0
14,30000484,14,90.0,88.000000,88.000000,4.358899,91.0,83.0

In [44]:
# 3-hour rolling mean
model_a["resp_rate_roll3_mean"] = (
    model_a.groupby("stay_id")["resp_rate"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).mean())
)

# 6-hour rolling mean
model_a["resp_rate_roll6_mean"] = (
    model_a.groupby("stay_id")["resp_rate"]
    .transform(lambda x: x.rolling(window=6, min_periods=1).mean())
)

# 3-hour rolling std
model_a["resp_rate_roll3_std"] = (
    model_a.groupby("stay_id")["resp_rate"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).std())
)

# 3-hour rolling max
model_a["resp_rate_roll3_max"] = (
    model_a.groupby("stay_id")["resp_rate"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).max())
)

# 3-hour rolling min
model_a["resp_rate_roll3_min"] = (
    model_a.groupby("stay_id")["resp_rate"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).min())
)

In [45]:
# 3-hour rolling mean
model_a["temperature_roll3_mean"] = (
    model_a.groupby("stay_id")["temperature"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).mean())
)

# 6-hour rolling mean
model_a["temperature_roll6_mean"] = (
    model_a.groupby("stay_id")["temperature"]
    .transform(lambda x: x.rolling(window=6, min_periods=1).mean())
)

# 3-hour rolling std
model_a["temperature_roll3_std"] = (
    model_a.groupby("stay_id")["temperature"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).std())
)

# 3-hour rolling max
model_a["temperature_roll3_max"] = (
    model_a.groupby("stay_id")["temperature"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).max())
)

# 3-hour rolling min
model_a["temperature_roll3_min"] = (
    model_a.groupby("stay_id")["temperature"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).min())
)

In [46]:
# 3-hour rolling mean
model_a["sbp_roll3_mean"] = (
    model_a.groupby("stay_id")["sbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).mean())
)

# 6-hour rolling mean
model_a["sbp_roll6_mean"] = (
    model_a.groupby("stay_id")["sbp"]
    .transform(lambda x: x.rolling(window=6, min_periods=1).mean())
)

# 3-hour rolling std
model_a["sbp_roll3_std"] = (
    model_a.groupby("stay_id")["sbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).std())
)

# 3-hour rolling max
model_a["sbp_roll3_max"] = (
    model_a.groupby("stay_id")["sbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).max())
)

# 3-hour rolling min
model_a["sbp_roll3_min"] = (
    model_a.groupby("stay_id")["sbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).min())
)

In [47]:
# 3-hour rolling mean
model_a["mbp_roll3_mean"] = (
    model_a.groupby("stay_id")["mbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).mean())
)

# 6-hour rolling mean
model_a["mbp_roll6_mean"] = (
    model_a.groupby("stay_id")["mbp"]
    .transform(lambda x: x.rolling(window=6, min_periods=1).mean())
)

# 3-hour rolling std
model_a["mbp_roll3_std"] = (
    model_a.groupby("stay_id")["mbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).std())
)

# 3-hour rolling max
model_a["mbp_roll3_max"] = (
    model_a.groupby("stay_id")["mbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).max())
)

# 3-hour rolling min
model_a["mbp_roll3_min"] = (
    model_a.groupby("stay_id")["mbp"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).min())
)

In [48]:
# 3-hour rolling mean
model_a["spo2_roll3_mean"] = (
    model_a.groupby("stay_id")["spo2"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).mean())
)

# 6-hour rolling mean
model_a["spo2_roll6_mean"] = (
    model_a.groupby("stay_id")["spo2"]
    .transform(lambda x: x.rolling(window=6, min_periods=1).mean())
)

# 3-hour rolling std
model_a["spo2_roll3_std"] = (
    model_a.groupby("stay_id")["spo2"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).std())
)

# 3-hour rolling max
model_a["spo2_roll3_max"] = (
    model_a.groupby("stay_id")["spo2"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).max())
)

# 3-hour rolling min
model_a["spo2_roll3_min"] = (
    model_a.groupby("stay_id")["spo2"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).min())
)

In [49]:
# 3-hour rolling mean
model_a["urineoutput_roll3_mean"] = (
    model_a.groupby("stay_id")["urineoutput_24hr"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).mean())
)

# 6-hour rolling mean
model_a["urineoutput_roll6_mean"] = (
    model_a.groupby("stay_id")["urineoutput_24hr"]
    .transform(lambda x: x.rolling(window=6, min_periods=1).mean())
)

# 3-hour rolling std
model_a["urineoutput_roll3_std"] = (
    model_a.groupby("stay_id")["urineoutput_24hr"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).std())
)

# 3-hour rolling max
model_a["urineoutput_roll3_max"] = (
    model_a.groupby("stay_id")["urineoutput_24hr"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).max())
)

# 3-hour rolling min
model_a["urineoutput_roll3_min"] = (
    model_a.groupby("stay_id")["urineoutput_24hr"]
    .transform(lambda x: x.rolling(window=3, min_periods=1).min())
)

In [50]:
print("Final Shape:", model_a.shape)
print("Total Features:", model_a.shape[1])

Final Shape: (851717, 91)
Total Features: 91

In [51]:
model_a.to_csv(
    "../data/processed/model_a_features.csv",
    index=False
)

print("Feature engineered dataset saved successfully!")

Feature engineered dataset saved successfully!

In [33]:
# Save enhanced feature dataset
output_path = "../data/processed/enhanced_feature_dataset.csv"

model_a.to_csv(output_path, index=False)

print("Enhanced feature dataset saved successfully.")
print("Shape:", model_a.shape)
print("Saved to:", output_path)

Enhanced feature dataset saved successfully.
Shape: (851717, 58)
Saved to: ../data/processed/enhanced_feature_dataset.csv