In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [3]:
model_a = pd.read_csv("../data/processed/model_a_features.csv")
cohort = pd.read_csv("../data/hf_dataset/sepsis_cohort.csv")

In [4]:
print(model_a.shape) # denotes the hourly observation of each patient with particular stay id
print(cohort.shape) #the patient's final medical chart. It tells you the start time and the exact time the event (sepsis) happened, but it doesn't show the hour-by-hour vitals.
model_a.head() # here  the Each row is one hourly observation of one patient during their ICU stay

(851717, 91)
(32971, 12)

,stay_id,hour,heart_rate,resp_rate,temperature,sbp,dbp,mbp,spo2,gcs,creatinine,bun,urineoutput_last,urineoutput_sum,urineoutput_24hr,wbc,hemoglobin,hematocrit,platelet,bands,sodium,potassium,chloride,bicarbonate,calcium,magnesium,aniongap,albumin,bilirubin_total,bilirubin_max,inr,pt,ptt,crp,lactate,pao2fio2ratio_novent,pao2fio2ratio_vent,glucose_lab,shock_index,map_calculated,bun_creatinine_ratio,spo2_deficit,heart_rate_prev,heart_rate_delta,resp_rate_prev,resp_rate_delta,temperature_prev,temperature_delta,sbp_prev,sbp_delta,mbp_prev,mbp_delta,spo2_prev,spo2_delta,gcs_prev,gcs_delta,heart_rate_roll3_mean,heart_rate_roll3_std,heart_rate_roll3_max,heart_rate_roll3_min,heart_rate_roll6_mean,resp_rate_roll3_mean,resp_rate_roll6_mean,resp_rate_roll3_std,resp_rate_roll3_max,resp_rate_roll3_min,temperature_roll3_mean,temperature_roll6_mean,temperature_roll3_std,temperature_roll3_max,temperature_roll3_min,sbp_roll3_mean,sbp_roll6_mean,sbp_roll3_std,sbp_roll3_max,sbp_roll3_min,mbp_roll3_mean,mbp_roll6_mean,mbp_roll3_std,mbp_roll3_max,mbp_roll3_min,spo2_roll3_mean,spo2_roll6_mean,spo2_roll3_std,spo2_roll3_max,spo2_roll3_min,urineoutput_roll3_mean,urineoutput_roll6_mean,urineoutput_roll3_std,urineoutput_roll3_max,urineoutput_roll3_min
0,30000484,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30000484,1,99.0,16.0,35.56,101.0,75.0,81.0,100.0,6.0,NaN,NaN,260.0,260.0,260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.980198,83.666667,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.000000,NaN,99.0,99.0,99.000000,16.000000,16.000000,NaN,16.0,16.0,35.56,35.56,NaN,35.56,35.56,101.000000,101.000000,NaN,101.0,101.0,81.000000,81.0,NaN,81.0,81.0,100.000000,100.0,NaN,100.0,100.0,260.0,260.0,NaN,260.0,260.0
2,30000484,2,88.0,14.0,NaN,92.0,43.0,55.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.956522,59.333333,NaN,0.0,99.0,-11.0,16.0,-2.0,35.56,NaN,101.0,-9.0,81.0,-26.0,100.0,0.0,6.0,NaN,93.500000,7.778175,99.0,88.0,93.500000,15.000000,15.000000,1.414214,16.0,14.0,35.56,35.56,NaN,35.56,35.56,96.500000,96.500000,6.363961,101.0,92.0,68.000000,68.0,18.384776,81.0,55.0,100.000000,100.0,0.000000,100.0,100.0,260.0,260.0,NaN,260.0,260.0
3,30000484,3,87.0,13.0,NaN,97.0,51.0,62.0,100.0,NaN,NaN,NaN,100.0,100.0,360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,56.5,NaN,NaN,NaN,NaN,0.896907,66.333333,NaN,0.0,88.0,-1.0,14.0,-1.0,NaN,NaN,92.0,5.0,55.0,7.0,100.0,0.0,NaN,NaN,91.333333,6.658328,99.0,87.0,91.333333,14.333333,14.333333,1.527525,16.0,13.0,35.56,35.56,NaN,35.56,35.56,96.666667,96.666667,4.509250,101.0,92.0,66.000000,66.0,13.453624,81.0,55.0,100.000000,100.0,0.000000,100.0,100.0,310.0,310.0,70.710678,360.0,260.0
4,30000484,4,92.0,18.0,NaN,128.0,66.0,82.0,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,0.718750,86.666667,NaN,2.0,87.0,5.0,13.0,5.0,NaN,NaN,97.0,31.0,62.0,20.0,100.0,-2.0,NaN,NaN,89.000000,2.645751,92.0,87.0,89.000000,15.000000,15.250000,2.645751,18.0,13.0,NaN,35.56,NaN,NaN,NaN,105.666667,104.500000,19.502137,128.0,92.0,66.333333,70.0,14.011900,82.0,55.0,99.333333,99.5,1.154701,100.0,98.0,360.0,310.0,NaN,360.0,360.0

In [8]:
print(cohort.columns.tolist())  # cohort is a subset of dataset and it is a dataset object it consist of data like patient in time and other information related to sepsis like sofa (simply it consist of crucial inforomation sepsis time and icuintime

['subject_id', 'hadm_id', 'stay_id', 'icu_intime', 'icu_outtime', 'sepsis_time', 'suspected_infection_time', 'window_end_uncapped', 'window_end', 'gender', 'age', 'n_hours']

In [9]:
cohort.head()

,subject_id,hadm_id,stay_id,icu_intime,icu_outtime,sepsis_time,suspected_infection_time,window_end_uncapped,window_end,gender,age,n_hours
0,18421337,22413411,30000484,2136-01-14 17:23:32,2136-01-17 04:53:08,2136-01-14 19:00:00,2136-01-14 18:10:00,2136-01-15 17:23:32,2136-01-15 17:23:32,M,92,24
1,12207593,22795209,30000646,2194-04-29 01:39:22,2194-05-03 18:23:48,2194-04-29 11:00:00,2194-04-29 01:00:00,2194-04-30 01:39:22,2194-04-30 01:39:22,M,44,24
2,16513856,24463832,30001446,2186-04-12 03:49:00,2186-04-13 19:45:47,2186-04-12 04:00:00,2186-04-11 08:20:00,2186-04-13 03:49:00,2186-04-13 03:49:00,M,56,24
3,10656173,25778760,30001555,2177-09-27 11:23:13,2177-09-28 18:26:00,2177-09-27 12:00:00,2177-09-27 07:21:00,2177-09-28 11:23:13,2177-09-28 11:23:13,F,34,24
4,17921898,28841024,30002415,2126-12-17 09:54:03,2126-12-18 10:15:01,2126-12-17 12:00:00,2126-12-16 15:05:00,2126-12-18 09:54:03,2126-12-18 09:54:03,F,72,24

In [11]:
### MERGING COHORT VALUES INTO MODEL_A
model = model_a.merge(
    cohort[
        [
            "stay_id",
            "icu_intime",
            "sepsis_time"
        ]

    ],
    on = "stay_id",
    how = "left"
)
print(model.shape)
model.head()

print(model[["hour",
             "icu_intime",
             "sepsis_time"]].head(10))

(851717, 93)
   hour           icu_intime          sepsis_time
0     0  2136-01-14 17:23:32  2136-01-14 19:00:00
1     1  2136-01-14 17:23:32  2136-01-14 19:00:00
2     2  2136-01-14 17:23:32  2136-01-14 19:00:00
3     3  2136-01-14 17:23:32  2136-01-14 19:00:00
4     4  2136-01-14 17:23:32  2136-01-14 19:00:00
5     5  2136-01-14 17:23:32  2136-01-14 19:00:00
6     6  2136-01-14 17:23:32  2136-01-14 19:00:00
7     7  2136-01-14 17:23:32  2136-01-14 19:00:00
8     8  2136-01-14 17:23:32  2136-01-14 19:00:00
9     9  2136-01-14 17:23:32  2136-01-14 19:00:00

In [12]:
model["icu_intime"] = pd.to_datetime(model["icu_intime"])
model["sepsis_time"] = pd.to_datetime(model["sepsis_time"])

In [13]:
# Current timestamp for each hourly record
model["current_time"] = (
    model["icu_intime"] +
    pd.to_timedelta(model["hour"], unit="h")
)

# Hours remaining until sepsis
model["hours_until_sepsis"] = (
    model["sepsis_time"] - model["current_time"]
).dt.total_seconds() / 3600

model[
    [
        "stay_id",
        "hour",
        "current_time",
        "sepsis_time",
        "hours_until_sepsis"
    ]
].head(15)

     stay_id  hour        current_time         sepsis_time  hours_until_sepsis
0   30000484     0 2136-01-14 17:23:32 2136-01-14 19:00:00            1.607778
1   30000484     1 2136-01-14 18:23:32 2136-01-14 19:00:00            0.607778
2   30000484     2 2136-01-14 19:23:32 2136-01-14 19:00:00           -0.392222
3   30000484     3 2136-01-14 20:23:32 2136-01-14 19:00:00           -1.392222
4   30000484     4 2136-01-14 21:23:32 2136-01-14 19:00:00           -2.392222
5   30000484     5 2136-01-14 22:23:32 2136-01-14 19:00:00           -3.392222
6   30000484     6 2136-01-14 23:23:32 2136-01-14 19:00:00           -4.392222
7   30000484     7 2136-01-15 00:23:32 2136-01-14 19:00:00           -5.392222
8   30000484     8 2136-01-15 01:23:32 2136-01-14 19:00:00           -6.392222
9   30000484     9 2136-01-15 02:23:32 2136-01-14 19:00:00           -7.392222
10  30000484    10 2136-01-15 03:23:32 2136-01-14 19:00:00           -8.392222
11  30000484    11 2136-01-15 04:23:32 2136-01-14 19:00:00           -9.392222
12  30000484    12 2136-01-15 05:23:32 2136-01-14 19:00:00          -10.392222
13  30000484    13 2136-01-15 06:23:32 2136-01-14 19:00:00          -11.392222
14  30000484    14 2136-01-15 07:23:32 2136-01-14 19:00:00          -12.392222

In [14]:
# 6-hour early warning target

model["target"] = (
    (model["hours_until_sepsis"] >= 0) &
    (model["hours_until_sepsis"] <= 6)
).astype(int)      # astype(int) convert true or false result into 1 or 0 . if patient likely to get sepsis between 1 to 6 hrs then label be 1 other than tht label will be 0

model[
    [
        "hour",
        "hours_until_sepsis",
        "target"
    ]
].head(15) # negative denotes the patient already have sepsis and positive denotes the patient likely to get sepsis for the patient tht doesnt have sepsis will be denotoed by NAT

    hour  hours_until_sepsis  target
0      0            1.607778       1
1      1            0.607778       1
2      2           -0.392222       0
3      3           -1.392222       0
4      4           -2.392222       0
5      5           -3.392222       0
6      6           -4.392222       0
7      7           -5.392222       0
8      8           -6.392222       0
9      9           -7.392222       0
10    10           -8.392222       0
11    11           -9.392222       0
12    12          -10.392222       0
13    13          -11.392222       0
14    14          -12.392222       0

In [16]:
### patient who developed sepsis
septic_patients = model[
    model["sepsis_time"].notna() ### identidies patient who have sepsis notna dropes the NAN in sepsis time which denotes the patient didnt get sepsis
    ]["stay_id"].unique()
### patient who never developed sepsis
non_septic_patients = model[
    model["sepsis_time"].isna()
]["stay_id"].unique()
print("Septic ICU stays:", len(septic_patients))
print("Non-septic ICU stays:", len(non_septic_patients))

Septic ICU stays: 32971
Non-septic ICU stays: 0

In [18]:
print(cohort["sepsis_time"].isna().sum())
print(cohort["sepsis_time"].describe())
print(cohort.head())

0
count                   32971
unique                  32253
top       2181-08-25 13:00:00
freq                        3
Name: sepsis_time, dtype: object
   subject_id   hadm_id   stay_id           icu_intime          icu_outtime  \
0    18421337  22413411  30000484  2136-01-14 17:23:32  2136-01-17 04:53:08
1    12207593  22795209  30000646  2194-04-29 01:39:22  2194-05-03 18:23:48
2    16513856  24463832  30001446  2186-04-12 03:49:00  2186-04-13 19:45:47
3    10656173  25778760  30001555  2177-09-27 11:23:13  2177-09-28 18:26:00
4    17921898  28841024  30002415  2126-12-17 09:54:03  2126-12-18 10:15:01

           sepsis_time suspected_infection_time  window_end_uncapped  \
0  2136-01-14 19:00:00      2136-01-14 18:10:00  2136-01-15 17:23:32
1  2194-04-29 11:00:00      2194-04-29 01:00:00  2194-04-30 01:39:22
2  2186-04-12 04:00:00      2186-04-11 08:20:00  2186-04-13 03:49:00
3  2177-09-27 12:00:00      2177-09-27 07:21:00  2177-09-28 11:23:13
4  2126-12-17 12:00:00      2126-12-16 15:05:00  2126-12-18 09:54:03

            window_end gender  age  n_hours
0  2136-01-15 17:23:32      M   92       24
1  2194-04-30 01:39:22      M   44       24
2  2186-04-13 03:49:00      M   56       24
3  2177-09-28 11:23:13      F   34       24
4  2126-12-18 09:54:03      F   72       24